name: Tag major version

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        default: 'v1.0.0'
      prefix:
        required: false
        type: string
        default: 'v'

jobs: 
  tag-version:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
    - name: Create Tag
      uses: actions/github-script@v7
      with:
        script: |
          console.log('hello');